// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error)
	GetAllCategoriesByUserID(ctx context.Context, userID pgtype.UUID) ([]GetAllCategoriesByUserIDRow, error)
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (string, error)
	GetUserSettingByID(ctx context.Context, id pgtype.UUID) (GetUserSettingByIDRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
