// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO 
    users (
        id,
        email,
        password,
        timezone,
        theme_color,
        language
    ) VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
`

type CreateUserParams struct {
	ID         pgtype.UUID    `json:"id"`
	Email      string         `json:"email"`
	Password   string         `json:"password"`
	Timezone   string         `json:"timezone"`
	ThemeColor ThemeColorEnum `json:"theme_color"`
	Language   string         `json:"language"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Timezone,
		arg.ThemeColor,
		arg.Language,
	)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT
    id,
    password,
    theme_color,
    language
FROM
    users
WHERE
    email = $1
`

type FindUserByEmailRow struct {
	ID         pgtype.UUID    `json:"id"`
	Password   string         `json:"password"`
	ThemeColor ThemeColorEnum `json:"theme_color"`
	Language   string         `json:"language"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.ThemeColor,
		&i.Language,
	)
	return i, err
}

const getUserSettingByID = `-- name: GetUserSettingByID :one
SELECT
    email,
    timezone,
    theme_color,
    language
FROM
    users
WHERE
    id = $1
`

type GetUserSettingByIDRow struct {
	Email      string         `json:"email"`
	Timezone   string         `json:"timezone"`
	ThemeColor ThemeColorEnum `json:"theme_color"`
	Language   string         `json:"language"`
}

func (q *Queries) GetUserSettingByID(ctx context.Context, id pgtype.UUID) (GetUserSettingByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserSettingByID, id)
	var i GetUserSettingByIDRow
	err := row.Scan(
		&i.Email,
		&i.Timezone,
		&i.ThemeColor,
		&i.Language,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE
    users
SET
    email = $1,
    timezone = $2,
    theme_color = $3,
    language = $4
WHERE
    id = $5
`

type UpdateUserParams struct {
	Email      string         `json:"email"`
	Timezone   string         `json:"timezone"`
	ThemeColor ThemeColorEnum `json:"theme_color"`
	Language   string         `json:"language"`
	ID         pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Email,
		arg.Timezone,
		arg.ThemeColor,
		arg.Language,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE
    users
SET
    password = $1
WHERE
    id = $2
`

type UpdateUserPasswordParams struct {
	Password string      `json:"password"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}
