// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/transaction/transaction_manager.go
//
// Generated by this command:
//
//	mockgen -source=usecase/transaction/transaction_manager.go -destination=usecase/transaction/mock_transaction_manager.go -package=transaction
//

// Package transaction is a generated GoMock package.
package transaction

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockITransactionManager is a mock of ITransactionManager interface.
type MockITransactionManager struct {
	ctrl     *gomock.Controller
	recorder *MockITransactionManagerMockRecorder
	isgomock struct{}
}

// MockITransactionManagerMockRecorder is the mock recorder for MockITransactionManager.
type MockITransactionManagerMockRecorder struct {
	mock *MockITransactionManager
}

// NewMockITransactionManager creates a new mock instance.
func NewMockITransactionManager(ctrl *gomock.Controller) *MockITransactionManager {
	mock := &MockITransactionManager{ctrl: ctrl}
	mock.recorder = &MockITransactionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITransactionManager) EXPECT() *MockITransactionManagerMockRecorder {
	return m.recorder
}

// RunInTransaction mocks base method.
func (m *MockITransactionManager) RunInTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTransaction indicates an expected call of RunInTransaction.
func (mr *MockITransactionManagerMockRecorder) RunInTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTransaction", reflect.TypeOf((*MockITransactionManager)(nil).RunInTransaction), ctx, fn)
}
